# FIXME: xxxに自身のユーザーIDを設定
service: sls-hands-on-user-xxx
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: ruby2.5
  stage: dev
  region: ap-northeast-1
  environment:
    DDB_TABLE: ${self:service}-task

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        # FIXME: xxxに自身のユーザーIDを設定
        - "arn:aws:dynamodb:ap-northeast-1:*:table/sls-hands-on-user-xxx-task"

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
  list:
    handler: handler.list
    events:
      - http:
          path: tasks
          method: get
  get:
    handler: handler.get
    events:
      - http:
          path: tasks/{id}
          method: get
  create:
    handler: handler.create
    events:
      - http:
          path: tasks
          method: post
  update:
    handler: handler.update
    events:
      - http:
          path: tasks/{id}
          method: patch
  delete:
    handler: handler.delete
    events:
      - http:
          path: tasks/{id}
          method: delete

resources:
  Resources:
    testTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-task
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
